### ISSUE TITLE
Setup CI and CD the way the PMO guide suggests.

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#11]
Good testing and dev workflows are one of the most important things we can provide.  Lets get them in place asap.

Here's what's needed:

- [x] - Figure out what tests are working and have `public/src/test.js` load them:

For example: http://localhost:5000/components/game/details/test.html currently passes.  There will be other passing tests inside the `src/components` folder.  Make sure they are all imported by `public/src/test.js`.  Make sure `src/test.html` runs and passes all tests.  

- [x] - setup testee to pass locally

[Something like this testee script](https://github.com/donejs/place-my-order/blob/master/package.json#L13) should work.  It should probably be in `public/package.json`.  But then make sure `package.json`'s test script runs `public/package.json`'s test script.  

- [x] - setup CI

Setup continous integration as is shown in the [PMO guide](https://donejs.com/place-my-order.html#section=section_Continuousintegration)

Then make sure everyone knows and starts using it to submit pull requests!

- [x] - setup CD

Finally, when master is merged, we want a deploy to `heroku` and `firebase`.  The instructions for this are in [the PMO Guide](https://donejs.com/place-my-order.html#section=section_Deploy).  As server-side rendering isn't turned on yet, you'll probably have to change [index.html](https://github.com/donejs/bitballs/blob/master/public/index.html) to point at firebase.  I'd create a `prod.html` that loads local production files.  This would make it easy for a developer to run in production with local production files.  

At the end of this, we should be able to submit pull requests to master, have all the tests pass, and when we merge into master, push out the latest production code.

**Comment by justinbmeyer** [comment]
![donejs_bitballs__a_basketball_tourney_application_](https://cloud.githubusercontent.com/assets/78602/13164454/fd2eaa64-d67a-11e5-83b3-5a87c4f2ac6c.png)

There seems to be a build error.

**Comment by jandjorgensen** [comment]
@justinbmeyer 
Build is failing on master: https://travis-ci.org/donejs/bitballs/branches
Do we want the badge to be current with "staging"?

**Comment by justinbmeyer** [comment]
Looks like it's failing at the deploy.
