### ISSUE TITLE
Make live-reload work again

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#12]
Currently, live-reload isn't working.

As this is a `donejs` app, we should make `donejs develop` start the node server, and live-reload correctly.

We aren't going to be using can-serve like [place-my-order does](https://github.com/donejs/place-my-order/blob/master/package.json#L15).

Instead, we need to probably need to add a script to [bitball's package.json](https://github.com/donejs/bitballs/blob/master/package.json#L7) that calls `node index.js` with an additional `--develop` option.  

`index.js` needs to be updated to start live-reload.  Here's how `can-serve` calls `steal-tools live-reload`: https://github.com/canjs/can-ssr/blob/master/bin/can-serve#L43.  My guess is that @James0x57 did something similar for RoomPlanner.  

I'm not a fan of having to spawn another process and having to depend on `infanticide` to kill it correctly.  Findout from @matthewp if there's a way to programmatically.   Perhaps a single node can only be one one process, hopefully not.

Bonus points if you can make this work in windows.  Everything will have to work in windows eventually.

**Comment by justinbmeyer** [comment]
we aren't going to be using `can-serve`, so this needs to be baked into starting `index` the right way.

**Comment by matthewp** [comment]
It can't be a single Node process because `can` is a singleton global, and we need to load it twice (once for server-side rendering and once to run the plugins in steal-tools).

**Comment by justinbmeyer** [comment]
@matthewp we could delete the module registry for `can` stuff and re-require.  This is something that `transpile` does.  Hacky.  But it would be nice to solve this.  Any other ideas?

**Comment by justinbmeyer** [comment]
Wait, aren't these loaded via `steal`?  Can't we have `ssr` and `live-reload` use a `.clone()` to load everything?  That way there should be a different `can`.

**Comment by matthewp** [comment]
Separate instances of steal will still share the same node `global`.  The problem is that can does `global.can = can`, but it looks like that can be turned off: https://github.com/canjs/canjs/blob/master/util/can.js#L10

The other issue IIRC was that can depends on a global `System` for `can.import`.

That being said this might be a fixable issue, I'm thinking there will be a many tiny cuts to it though.

**Comment by justinbmeyer** [comment]
Keeping this open until the separate node process thing is figured out.

@matthewp "The problem is that can does global.can = can"

Why would this be a problem?  Any code we are using in any of our apps should hit the `can` imported by the module over the global `can`.

**Comment by justinbmeyer** [comment]
Closing for #31.  @matthewp lets move any future conversation there.
