### ISSUE TITLE
No feedback after registering a new user

### ISSUE THREAD

**Issue by matthewp** [donejs/bitballs#139]
Go to http://localhost:5000/register and enter an email and password.  I would expect it to forward you to an account page or show a success message or something, but does none of those things.

**Comment by James0x57** [comment]
It logs you in, and takes you to the account page where it prompts you to verify the user:
<img width="1379" alt="screen shot 2016-03-10 at 10 50 47 am" src="https://cloud.githubusercontent.com/assets/7545075/13677046/0ff92a28-e6ae-11e5-9d32-cd294c9c6da3.png">
This is on the staging branch, not sure if it's in master yet but this should be fine
