### ISSUE TITLE
Build is breaking.

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#15]
```
OPENING: /Users/justin/dev/bitballs/public/package.json!npm
Potentially unhandled rejection [6] Error: Error loading "can-wait" at file:/Users/justin/dev/bitballs/public/can-wait.js
Error loading "can-wait" from "index.stache!done-autorender@0.6.1#autorender" at file:/Users/justin/dev/bitballs/public/index.stache
ENOENT: no such file or directory, open '/Users/justin/dev/bitballs/public/can-wait/index.js'
    at Error (native)
```

**Comment by justinbmeyer** [comment]
Works if I add `"can-wait"` to my `dependencies`.

**Comment by matthewp** [comment]
If you're using 0.14.0-pre you need can-wait as a dependency.  This is because your index.stache does depend on can wait.  Previously this worked without it being a dependency because the npm plugin would look up packages by name if it was not found in your own dependencies; in 0.14 it doesn't do that any more.  It is a dependency in the next version of donejs now: https://github.com/donejs/cli/blob/minor/package.json#L57

**Comment by justinbmeyer** [comment]
@matthewp Even if `index.stache` depends on `can-wait`, I'm not sure why progressive loading should be able to find it.  Shouldn't it look for `can-wait`?

If not, this seems like a step backwards from the old behavior.  I'm probably missing something though,

**Comment by matthewp** [comment]
> If not, this seems like a step backwards from the old behavior. 

What's the use-case for importing a package you don't depend on? I preserved all of the existing uses that we had tests for, globalBrowser was the big one. 

Looking up by package name causes bugs like if you are trying to import `util/extend` from your project but there is an npm package `util` 3 levels deep, you'll get that instead. https://github.com/stealjs/steal/issues/577

**Comment by justinbmeyer** [comment]
Maybe I'm missing something, but `done-autorender` depends on `can-wait`.  I shouldn't have to import `done-autorender`'s dependencies.

**Comment by justinbmeyer** [comment]
Basically, if I depend on `moduleA`, I shouldn't have to care what `moduleA` depends on.

**Comment by matthewp** [comment]
Ah, I understand the question now. done-autorender transforms your index.stache into something like:

```js
define(["can/view/stache/stache", "can-wait" ....
```

So your app must have dependencies on can and can-wait, because it is your app's dependency, not done-autorender's (done-autorender doesn't use these deps itself).

**Comment by justinbmeyer** [comment]
Is there a way to make this work? Seems like this might be a common pattern.

**Comment by matthewp** [comment]
I can't think of a way that doesn't cause the bug described in https://github.com/stealjs/steal/issues/577

**Comment by justinbmeyer** [comment]
Could extensions at least write out the dependency in a way that works?

**Comment by justinbmeyer** [comment]
@matthewp anyway you can update done-autorender?  I think you made an issue elsewhere.  I assumed it was in autorender, but couldn't find it.  I'm assigning this issue to you.  Not high priority.  But a nice to have.

**Comment by matthewp** [comment]
Does this app have a smoke test that loads the main app? That would confirm that it works when removing can-wait.  I don't think it does, need something like this: https://github.com/donejs/place-my-order/blob/master/src/test/functional.js

**Comment by justinbmeyer** [comment]
It has automated tests.  Why is a smoke test needed when you can just run `npm run test`?

**Comment by justinbmeyer** [comment]
cc @jandjorgensen

**Comment by matthewp** [comment]
> Why is a smoke test needed when you can just run npm run test?

I'm guessing none of those tests use done-autorender, it's typically only used for the main app.

**Comment by matthewp** [comment]
Actually this a build problem, so never mind. Can test by running the build.
