### ISSUE TITLE
Tournament details page does not reattach in the client

### ISSUE THREAD

**Issue by matthewp** [donejs/bitballs#172]
In client side reattachment we wait for all asynchronous events to finish just like on the server, so that when we replace the DOM there is no flash.  On the the tournament details page the Zone never resolves as complete.  Possibly a can-zone bug, I'm looking into it.

**Comment by matthewp** [comment]
This is caused by can/view/bindings use of MutationObservers.  What happens is, a `setTimeout` is called and a `clearTimeout` is run within the MutationObserver callback. Because that callback is not tracked, the clearTimeout doesn't run "in the Zone" and therefore the wait counter is not decremented.

2 possible solutions:

## Quick and dirty

Update can/view/bindings to be "Zone aware", when the mutation observer is used it would be changed to do:

```js
var onMutation = Zone.current.wrap(function (mutations) {
							
  if(stickyCompute) {
    set(stickyCompute());
  }
							
  updater();
});
```

Of course checking to make sure can-zone is being used and there is a current zone.

## More robust

The more robust solution would be implementing https://github.com/canjs/can-zone/issues/60 and https://github.com/canjs/can-zone/issues/61

This would set up super-dependencies so that MutationObserver is wrapped before canjs is loaded. This is needed because canjs uses local reference variables for MutationObserver.

**Comment by matthewp** [comment]
I have this solved, the question is how to use it.  This new thing is a super dependency that needs to be loaded before canjs is (or anything else that is saving setTimeout, etc. in local variables.

I can submit a PR here that does:

```json
{
  "system": {
    "configDependencies": [
      "node_modules/can-zone/register"
    ]
  }
}
```

This sucks, but works today.

Here's 2 possible solutions:

## Allow direct dependencies to add to configDependencies

This means that a dependency (like can-zone) could have:

```js
"system": {
  "configDependencies": [
    "./register
  ]
}
```

This presents a couple of problems:

### Would have to be a direct dependency

This is because of progressively fetching package.json. can-zone is not currently a direct dep, but could be.

### Need to normalize the path

This is not a huge deal, but would need to use `./`

### Dependencies often have dev configDependencies

The DoneJS plugin generator will add `live-reload` for development.  We don't want to force live-reload on everyone because they are dependending on a package that has that in their config.

Possible solution here is to only include configDependencies of dependencies if they start with `./`.

The more I think about it, the more I like this solution.

**Comment by justinbmeyer** [comment]
I think it's fine to be in the root package.json.

**Comment by matthewp** [comment]
You think what is fine?

**Comment by justinbmeyer** [comment]
```
{
  "system": {
    "configDependencies": [
      "node_modules/can-zone/register",
      ...
    ]
  }
}
```
