### ISSUE TITLE
Functionality Images

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#225]
In the intro section of https://donejs.com/bitballs.html, there should be images for the main activities of the application:

![donejs_-_bitballs_app](https://cloud.githubusercontent.com/assets/78602/13953632/ee8defc0-f00a-11e5-9165-53cc11271169.png)

**Comment by akagomez** [comment]
This looks to be addressed already: 

![](https://i.imgur.com/pBAQkn8.png)
