### ISSUE TITLE
Update Guides page with Bitballs

### ISSUE THREAD

**Issue by tomgreever** [donejs/bitballs#239]
I added placeholder content for Bitballs on the `guides.html` page because I needed to add the thumbnail image that matched the others. But unless this guide is actually about lawn maintenance, we should consider re-writing it. 
![screen shot 2016-03-24 at 8 05 35 am](https://cloud.githubusercontent.com/assets/326843/14017715/6285758c-f197-11e5-9945-b7aada6724d5.png)

**Comment by justinbmeyer** [comment]
@tomgreever I'm confused, there already is Bitballs content on this page: https://donejs.com/Guides.html

**Comment by justinbmeyer** [comment]
I'm leaving what I had. I'd like to show the page with youtube.  In general, I think all of these thumbnails should be much bigger.

**Comment by tomgreever** [comment]
Oh, I must have been using an old version of that page on the `bitballs` branch. Ok, I'll update the image and remove my placeholder
