### ISSUE TITLE
Memory leak in <tournament-details>

### ISSUE THREAD

**Issue by matthewp** [donejs/bitballs#260]
There's a memory leak in the &lt;tournament-details&gt; ViewModel which is created by binding to the Game model's length property. Because the game model is in the instance store this binding is never torn down. Would be fixed by https://github.com/canjs/can-define/issues/15

Direct fix will be to move the binding to the component's inserted event, and removed in the removed event.

**Comment by frank-dspeed** [comment]
I think this can be clossed right?

**Comment by justinbmeyer** [comment]
yep, thanks!
