### ISSUE TITLE
Publish documentation to github pages

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#27]
Make a script that generates the documentation and publishes it to a `gh-pages` branch.

This [makefile](https://github.com/bithubapp/taylored-wines/blob/master/Makefile) serves as a good example.

The script should:

- checkout gh-pages
- run documentjs
- force add the `docs` folder and selective parts of `node_modules` needed for demo and test pages to run: `can`, `jquery`, `steal`, `can-connect`, there's probably a lot more.
- make a commit and force push it to `gh-pages`
- check back out `master` or better would be the old working branch
- delete gh-pages

This should run with CD and be pushed out every time someone merges into master.

**Comment by akagomez** [comment]
Do you mean for this to be a Makefile in the bithub repo too?

How do you want to configure the documentation dependencies? (edit the script directly, require a configuration file, read from `package.json`)

Where do you want this script (or potentially Makefile) to be stored in the repo? (`./`, `./scripts`, etc)

How would you like to execute the script? (`npm run publish-docs`, `node publish-docs.js`, `make publish-docs`, etc)

**Comment by akagomez** [comment]
Does this script belong to the `/public` package, or the root package?

**Comment by akagomez** [comment]
> Do you mean for this to be a Makefile in the bitballs repo too?

Yes, this should be a Makefile.

> How do you want to configure the documentation dependencies? (edit the script directly, require a configuration file, read from package.json)

The documentation dependencies should be written inline with the publish script. 

> Where do you want this script (or potentially Makefile) to be stored in the repo? (./, ./scripts, etc)

This should be stored in the root. 

> How would you like to execute the script? (npm run publish-docs, node publish-docs.js, make publish-docs, etc)

`make publish-docs` because it's uniquely "ugly". 

> Does this script belong to the /public package, or the root package?

Root package.
