### ISSUE TITLE
Development mode doesn't package players in players page

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#277]
To reproduce:

 - clone a fresh copy, npm install
 - run `donejs develop`
 - go to players page and refresh.
 - Checkout the source, you'll see nothing between the `<tbody>` as shown here:

![blob](https://cloud.githubusercontent.com/assets/78602/21274820/b673a054-c38f-11e6-9a43-9263982cc888.png)

Reported on gitter: https://gitter.im/donejs/donejs?at=5854306c0730ce6937d37959

**Comment by justinbmeyer** [comment]
Also in production, the players are in the html `1`, but there's still a request for _players?order=name_ `2`


![cursor_and_bitballs___players_and_aerotwist_-_ _when_everything_s_important__nothing_is__](https://cloud.githubusercontent.com/assets/78602/21275229/5be946a0-c391-11e6-8f14-8668b8c0ecbb.png)

**Comment by gKreator** [comment]
For me it does this whether or not I run it as 

`NODE_ENV=production donejs start`
`NODE_ENV=production node index`
`npm start`
`node index`

![image](https://cloud.githubusercontent.com/assets/1431487/21276194/e77a97ec-c395-11e6-9c64-3c7da27e6590.png)

And yes the live BitBalls, makes that extra ajax request.

**Comment by matthewp** [comment]
I might be confused but I don't see the bug. Either when working locally or when viewing production: view-source:http://bitballs.herokuapp.com/players

I see players listed there. Did the bug go away on its own?

**Comment by justinbmeyer** [comment]
You can see the players, but ssr doesn't work as expected.

**Comment by matthewp** [comment]
Can you explain more? The issue as described in the first post isn't reproducible any more. What is is unexpected here?

**Comment by justinbmeyer** [comment]
@matthewp lets pair on it tomorrow.  What branch are you using?

**Comment by justinbmeyer** [comment]
@matthewp the issue still exists in production.  You can see the players request still.  This shouldn't happen as it should be in the XHR cache.

**Comment by matthewp** [comment]
I'm able to see the unexpected request now, debugging.

**Comment by matthewp** [comment]
This appears to be fixed on http://bitballs.herokuapp.com/players
