### ISSUE TITLE
Player stats

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#286]
When a player is clicked on:

![cursor_and_bitballs___players](https://cloud.githubusercontent.com/assets/78602/26656644/88372152-4625-11e7-8bfd-9585d884b6f2.png)

The user should be taken to a player profile page.

It should list their name, and stat totals by tournament.

Available stats:

![cursor_and_bitballs___game](https://cloud.githubusercontent.com/assets/78602/26656734/eb6dd68a-4625-11e7-80f1-7703fe0839f2.png)

**Comment by jamiemccue** [comment]
@justinbmeyer Can you give an example of stat totals by tournament?

**Comment by jamiemccue** [comment]
@justinbmeyer does a layout like this work for you? 
![player-stats](https://cloud.githubusercontent.com/assets/381138/26739747/e79af05c-4787-11e7-8dde-ad6c738b6dd6.png)

- stats could go full width left right

**Comment by justinbmeyer** [comment]
looks great

**Comment by jamiemccue** [comment]
![player-stats](https://cloud.githubusercontent.com/assets/381138/26740376/1ded19e4-478a-11e7-9106-5ff25d607e61.png)

**Comment by jamiemccue** [comment]
Link to PSD if needed: https://drive.google.com/a/jupiterjs.com/file/d/0B9uYesPecByGTFZYV0pNdXl2cE0/view?usp=sharing

**Comment by christopherjbaker** [comment]
fixed with #291
