### ISSUE TITLE
Add an "or register" link next to to the Login button

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#45]
Add a "or register" link next to the login button that takes people to the "Create User" page.  

![localhost_5000_dev_html__user](https://cloud.githubusercontent.com/assets/78602/13164329/f53d4938-d679-11e5-969a-d4f1d2884de3.png)

Next:

- Change the routing so the `/user` page is now `/register.
- Instead of saying "Create User", it says "Register new user".
- Change the "Create" button to "Register".

![cursor_and_localhost_5000_dev_html__user](https://cloud.githubusercontent.com/assets/78602/13164360/3edc36c6-d67a-11e5-9989-87b5665e8b62.png)

**Comment by akagomez** [comment]
Closed via #63.
