### ISSUE TITLE
Unable to update user's password.

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#48]
Steps to reproduce.

1. Restart your server so you are logged out.
2.  Login as a user.
3.  Go to `#!user` and enter a new password.
4.  In the "network" tab, you'll notice a 404 error.

**Comment by justinbmeyer** [comment]
https://github.com/canjs/canjs/blob/master/map/define/doc/examples/make-model-year.html#L110

**Comment by jandjorgensen** [comment]
Update: now requires adding an account page

**Comment by justinbmeyer** [comment]
closing for #81
