### ISSUE TITLE
Quickly creating tournaments doesn't show 

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#54]
There might be a problem with can-connect.

If you enter a date in the New Tournament __Date__ field and hit "Create" twice quickly, only one tournament shows up despite making two requests.

Likely this is due to `.save()` being called twice on the same instance.  

This is probably fixed by using `{{isSaving}}` to disable the create button.

![cursor_and_localhost_5000_dev_html__](https://cloud.githubusercontent.com/assets/78602/13165721/f43dd014-d685-11e5-8c8c-4f827c53dd12.png)

**Comment by akagomez** [comment]
Closed via #64.
