### ISSUE TITLE
Allow YouTube URL form to take actual youtube URL or youtube key

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#55]
![cursor_and_localhost_5000_dev_html___tournamentid_6](https://cloud.githubusercontent.com/assets/78602/13165779/7a62daf4-d686-11e5-89c8-52f6d36a50bb.png)

The YouTube URL form actually only works if you paste a youtube key like `y5sdfa834lJ`.  This key is what should be stored in the DB, but we should allow people to paste either the key or the URL and it works.

**Comment by akagomez** [comment]
Closed via #85.
