### ISSUE TITLE
Handle model/server errors

### ISSUE THREAD

**Issue by jandjorgensen** [donejs/bitballs#71]
For #46, #48, #51, and #53, we need to propagate server errors to display them on the client.

Since we're in the "make it work" phase and not the "make it pretty" phase, this should just include an error message by the submit button on the relevant forms.

**Comment by jandjorgensen** [comment]
Initial/suggested approach:
Add an `error-message` component that takes the relevant model instance as property and adds callbacks that displays errors when they occur.

Reasoning:
Often times, there is a lot of `.fail` spaghetti code that gets copied and pasted between form pages. An isolated error-message component still allows for special error-handing behavior in the form component's ViewModel, but it treats error messaging as a separate concern.

**Comment by justinbmeyer** [comment]
@jandjorgensen I don't think it needs to be a separate component.  It should be something as simple as making sure the promise is added to the `viewModel` and having:

```
{{#if savePromise.isRejected}}
   <p>{{savePromise.reason}}</p>
{{/if}}
```

in the template.
