### ISSUE TITLE
Make file organization match guide.

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitballs#75]
- [x] remove db_client, app.json
- [x] move bookshelf.js, is it possible to use database.json?
- [x] move app.js into services
- [x] rename post_install to install.js
- [x] rename public/styles.less to public/app.less
- [x] remove stylesheets folder
- [x] remove .yo-rc, lang-logo.png, node.svg, 
- [x] Organize fixtures and models into final folder pattern. #121

**Comment by akagomez** [comment]
I have questions about this task: 

> move bookshelf.js, is it possible to use database.json?

- Where should I move `bookshelf.js` to? The guide doesn't specify where it belongs. 
- Do you mean to replace `bookshelf.js` with `database.json`? Or do you mean to pass a JSON configuration to `knex` as is implied in the Bookshelf documentation? 

  ```
var knex = require('knex')(dbConfig);
```

**Comment by justinbmeyer** [comment]
Move bookshelf into `models`.

So `database.json` is configuring `db-migrate`.  And `bookshelf.js` is configuring our Bookshelf models.

The configuration should be the same.  I wonder if it's possible for `bookshelf.js` to read `database.json` and call `knex` accordingly.

**Comment by akagomez** [comment]
Closed via #140.
